### ISSUE TITLE
Create a <File> component

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/shape-up-process#26]
The template author should be able to use a component representing the current file being rendered. We can call this component `<File>`. It should take —at least— the following props:

* `name`: It represents the name of the file in the output.
* `permissions`: It represents the permissions of the file in the output.

### Hints

* Consider using a standard way of defining file permissions, like the Unix one. Make sure it's applicable to all the major operating systems.
* Consider starting the docs, tests, and code of this component **before** any other tasks are finished, to increase work parallelization.

**Comment by jonaslagoni** [comment]
Some questions regarding the props:

* how does the `name` prop expect to work together with the file name template `$$schema$$` from the generator?
* Also if no `name` is provided I would assume the actual file name of the template is what is being used as name for the rendered file? 
* Are the `permissions` prop really relevant? What's the use-case for actually stating them from a templater's POV?

**Comment by fmvilas** [comment]
> how does the name prop expect to work together with the file name template $$schema$$ from the generator?

I'd expect the prop `name` to replace the `$$schema$$` functionality.

> Also if no name is provided I would assume the actual file name of the template is what is being used as name for the rendered file?

Yes. Defaults to current behavior where it might get the name from the file or from the `$$schema$$` syntax.

> Are the permissions prop really relevant? What's the use-case for actually stating them from a templater's POV?

Some files need to be executable (scripts, for instance). Skip this part for now if you feel it's gonna take a lot of time.

**Comment by jonaslagoni** [comment]
> > Are the permissions prop really relevant? What's the use-case for actually stating them from a templater's POV?
> 
> Some files need to be executable (scripts, for instance). Skip this part for now if you feel it's gonna take a lot of time.

Its not that, I feel this is a security risk, I see what you mean, however if script files are generated I expect myself as a user to have to give the file access to run. A malicious template owner might add a script file hidden somewhere, which are executing once the  user tries to use the "normal" library. The user would have no idea that is it happening since we already gave the file execution permissions. 

I know that at the moment hooks can easily be used to implement the same functionality, but I can imagine that would change as well in some way :shrug: In my mind these form for code generators are super awesome but also the perfect opportunity for malicious actors to inject anything into a persons computer.

But I can also see the usefulness in having this prop.

**Comment by fmvilas** [comment]
It's already a problem without hooks too. For instance, right now (without React) if the template file is executable, it will be copied as executable too if it's marked as `nonRenderableFile` (see [this](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file)).

It's a valid concern but it's also true it has nothing to do with the task at hand so I'd not worry about it now. Feel free to create an issue on the Generator to raise your concern.

**Comment by jonaslagoni** [comment]
> It's already a problem without hooks too. For instance, right now (without React) if the template file is executable, it will be copied as executable too if it's marked as `nonRenderableFile` (see [this](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file)).

This is not true, the files are never copied with execution permissions even if they did since you install the template (before generating the files) all files are given `-rw-rw--r--` and once generated they receive `-rw-r--r--`. This is regardless of whether `nonRenderableFile` are sat or not. So even if the user manually changes the templates file permissions before generating the files it it still does not preserve the permissions :slightly_smiling_face:

**Comment by jonaslagoni** [comment]
Down to the actual `permission` configuration would one rather define it as `0o777` or `"777"`? 

`0o` is to describe the number as octal.

**Comment by fmvilas** [comment]
> This is not true, the files are never copied with execution permissions

Seems to be an OS issue? https://github.com/nodejs/node/issues/26936. It's respecting permissions for me on Mac OS X.

> Down to the actual permission configuration would one rather define it as 0o777 or "777"?

What about an JS object like:

```js
{
  executable: true,
  user: {
    read: true,
    write: true,
  },
  group: {
    read: true,
    write: true,
  }
}
```

And depending on the OS it will convert it down to the corresponding code.

**Comment by magicmatatjahu** [comment]
Done by https://github.com/asyncapi/generator-react-sdk/commit/c884869529438216fa6b2235036c9520e3a9d225 commit
