### ISSUE TITLE
Create and define the shape for common input model

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/shape-up-process#51]
Think about shape of the input model, what it should include to handle common types in languages like classes, properties, methods etc.

**Comment by jonaslagoni** [comment]
/progress 15 started and trying to figure out the optimal shape to use as a common model for rendering.

**Comment by jonaslagoni** [comment]
# The common model setup

The following are the results for figuring out the common input model which are to be provided to the rendering of data models.

**references**
- https://json-schema.org/understanding-json-schema
- https://json-schema.org/draft/2019-09/json-schema-validation.html
- https://github.com/asyncapi/shape-up-process/issues/42

**vocabulary** - terms I use throughout this comment. 
- Combination schemas
    - Schemas which contain the following keywords: `allOf`, `anyOf`, `oneOf`
- Conditional schemas
    - Schemas which contain the following keywords: `if`, `then`, `else`
- JSON Schema
    - When I refer to JSON Schema I always reference JSON Schema Draft 7

**Requirements**
- Should be able to handle multiple types of inputs
    - AsyncAPI, json schema, avro, w/e
- Should make it easier to use from a model template perspective so they don't have to do any pre-processing to render the model.
- See https://github.com/asyncapi/shape-up-process/issues/42 for further requirements



I cannot find any other optimal way to structure the common input then to use the existing JSON Schema specification, however we do need to make some manipulation before sending the model to the model rendering. The reason behind this is that we dont want each renderer to have to figure out the very basic information about what model are to be generated, it should be as simplified as possible.

The reason why we should keep JSON Schema is because there is no reason to introduce a completely new way of representing the internal model representation. If we would have designed it from scratch we would have changed some properties, meanings etc but boiled down it is basically JSON Schema.

![Data model -Input(1)](https://user-images.githubusercontent.com/13396189/105390900-d9073c80-5c19-11eb-870c-ea85940cbb8a.png)


Common model wrapper should have the following properties:
- `models`
    - Map of simplified common models using <`$id`, Schema> type.
- `customizations`
    - The structure of how to customize the output
    - to be defined in https://github.com/asyncapi/shape-up-process/issues/53
- `originalSchema`
    - The original JSON Schema

Even though we reference the whole Schema on the diagram, we need to figure out if we just want to use `Schema` or introduce something like `CommonModel` which only contains accessible properties. Common JSON schema model as a simplified version should ONLY include the following keywords for now:
- `$id`
- `type`
- `enum`
- `properties`
    - in the format <property name, Common model>
- `items`
    - Common model
- `additionalProperties`
    - Common model
- `$ref`
    - reference to another Common model
- `x-original-schema`
    - the original JSON Schema object
- `x-extend`
    - if the model should extend some other model
    - The string should be a reference to a model with `$id`

`Schema` class is at the moment depicts the full JSON Schema.

# JSON Schema 
Because there are so many different ways to structure JSON schema we need a simplification stage which manipulates the existing JSON Schema into a simplified and minimal version. In the simplification stage the main point is to return an absolute minimal representation of the data model that the underlying renderer can use. 


This means making the following transformations:

- Remove all combinations schemas and merge all affected.
- Remove and merge conditional schemas
- Go through all `properties`, `items` and `additionalProperties` schemas and **process**
- All schemas with type Object should be turned into another common model
- Infer type from `enum` and `const` since they can be defined without explicit type.
- Others? Everything is to be defined in https://github.com/asyncapi/shape-up-process/issues/45.

The following JSON Schema keywords provides a loosely typed data model and MUST be used to : `properties`, `enums`, `items`, `additionalProperties`, `additionalItems`, `type`, conditional schemas, combination schemas, `patternProperties`, schema dependencies, `not`.

These are the keywords for which provides a strongly typed data model (validation) and are SHOULD haves: `format`, `length`, `regular expressions`, `multipleOf`, range, `uniqueItems`, `required`, `const`, `default`, conditional schemas, combination schemas. `additionalItems`, property dependencies, `propertyNames`, `readOnly`, `writeOnly`



## Examples
The following are examples of input JSON Schemas which should result in a simplified common model to show the principle behind the idea.

### Example 1 - Applying sub-schemas conditionally
Given the following JSON Schema:

```json
{
  "type": "object",
  "properties": {
    "street_address": {
      "type": "string"
    },
    "country": {
      "enum": ["United States of America", "Canada"]
    }
  },
  "if": {
    "properties": { "street_address": { "const": "United States of America" } }
  },
  "then": {
    "required": ["country"],
    "properties": { "country": { "enum": ["Canada2", "something else"] } }
  }
}
```

I would expect the minimal common model output to be:
```json
{
  "type": "object",
  "required": ["country"],
  "properties": {
    "street_address": {
      "type": "string"
    },
    "country": {
      "enum": ["United States of America", "Canada", "Canada2", "something else"]
    }
  }
}
```


All the rules for merging these are yet to be defined.


### Example 2 - Multiple common models
Given the following JSON Schema which contains multiple objects

```json
{
  "$id": "Example2",
  "type": "object",
  "properties": {
    "street_address": {
      "type": "object",
      "properties": {
        "floor": {
          "type": "number"
        }
      },
    },
    "country": {
      "enum": ["United States of America", "Canada"]
    }
  }
}
```

I would expect the minimal common model output to be
```json

{
  "type": "object",
  "properties": {
    "street_address": {
      "$ref": "street_address"
    },
    "country": {
      "enum": ["United States of America", "Canada"]
    }
  }
}
{
  "$id": "street_address",
  "type": "object",
  "properties": {
    "floor": {
      "type": "number"
    }
  }
}
```
Now, I am using `$id` to illustrate thats it gets split into two separate models. The naming of the ids should most likely follow our own parser. Also in terms of anonymous schema naming such as https://github.com/asyncapi/parser-js/issues/176.

### Example 3 - Combination and extending schemas
Given the following example schema:
```json 
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": {
      "allOf": [
        { "$ref": "#/definitions/address" },
        { "properties":
          { "type": { "enum": [ "residential", "business" ] } },
          "required": ["type"]
        }
      ]
    }
  }
}
```

I would expect the minimal common model output to be divided into 3 schemas:


```json 
[
  {
    "$id": "address",
    "type": "object",
    "properties": {
      "street_address": { "type": "string" },
      "city":           { "type": "string" },
      "state":          { "type": "string" }
    },
    "required": ["street_address", "city", "state"]
  }
  {
    "$id": "shipping_address",
    "x-extend": "address", 
    "type": "object",
    "properties": {
      "type": { "enum": [ "residential", "business" ] }
    },
    "required": ["type"]
  }
  { 
    "type": "object",
    "properties": {
      "billing_address": { "$ref": "address" },
      "shipping_address": { "$ref": "shipping_address"}
    }
  }
]
```

This example really shows the common model creation in action which enables us to create both polymorphism and inheritance but also inline structures if desired.


### Example 4 - Enums of different types
It is possible to support enums of different types such as the following
```json 
{ 
  "properties": { 
    "type": { 
      "enum": [ "residential", "business", 123 ] 
    }
  }
}
```
Question is how do we make this easier for the model renderer. Do we really care?


## True and false schemas 
Defining a schema as `true` or `false` means accept all or reject all respectively. 
```json
{
    "type": "object",
    "properties": {
        "foo": true
    }
}
```
Which would result in the simplified version
```json
{
    "type": "object",
    "properties": {
        "foo": {
          "type": ["string", "object", "number", "array", "boolean", "null"]
        }
    }
}
```

Regarding `false` schemas I would assume that we should use `"type": ["null"]`?

## Decisions and questions

1. How do we want to simplify `true` and `false` schemas?
    - Add a custom type such as `any`
    - Give the type of the schema all possible values, so the model renderer can figure out what to do with them. Since some languages support one or more types.
        - How do we handle `false` schemas?
              - Using `"type": ["null"]`?
1. How do we want to reference other common models?
    - `$ref`
1. How do we want to model `enums`?
    - I don't see any reason why it cant be as is. Even if enums can contain multiple types
1. Should we already now introduce an `extend` keyword?
    - Yes, because of the natural way we want to normalize schemas requires this feature.
    - A simple copy of the schema and merging of it would suffice
1. Should we introduce a special class such as `CommmonModel` which ONLY contains the used properties? 
    - I would say yes, to ensure people know exactly what properties are accessible.

**Comment by jonaslagoni** [comment]
/progress 45 Figured most of the things out how to depict the common input model, still got a hanging issue regarding the structure and use of something like `CommonModel` instead of `Schema`. We also added the initial repository for [the model generation](https://github.com/asyncapi/generator-model-sdk/).

**Comment by magicmatatjahu** [comment]
Awesome! About questions:

> How do we want to simplify true and false schemas?

I am in favor of a type array solution.

> How do we handle false schemas?

Typescript has something like `never` type, but not all languages ​​have an equivalent for that.

> How do we want to model enums? I don't see any reason why it cant be as is. Even if enums can contain multiple types.

Have in mind that some languages like GoLang has enums only for one type, string, int etc. I have no idea how to workaround it.

> Should we already now introduce an `extend` keyword?

Better than `allOf` 😄 

Good stuff man!

**Comment by jonaslagoni** [comment]
> Have in mind that some languages like GoLang has enums only for one type, string, int etc. I have no idea how to workaround

Thats an implementation issue we will handle in the GoLang renderer I think 😄 But yea, we need to get a bit creative there probably.


@magicmatatjahu regarding this question:

> Should we introduce a special class such as `CommmonModel` which ONLY contains the used properties?
> 
>     * I would say yes, to ensure people know exactly what properties are accessible.

Do you think we should create a class which only contains used keywords, or just keep using `Schema` class? 🤔

**Comment by magicmatatjahu** [comment]
@jonaslagoni Yep, new class will be better to handle not only schema related fields, but also not-related like modifications etc.

**Comment by jonaslagoni** [comment]
Alright, this will be the updated input data model setup @magicmatatjahu 

![Data model -Input(2)](https://user-images.githubusercontent.com/13396189/105480069-8ecb9d00-5ca5-11eb-814b-81c9c3a02117.png)

**Comment by magicmatatjahu** [comment]
@jonaslagoni great! I have one question: `Schema` class extends `CommonSchema` or `Schema` has a one field with `CommonSchema` model?

**Comment by jonaslagoni** [comment]
/progress 75 defined basic models and started setting up the process interactions.

**Comment by jonaslagoni** [comment]
/progress 99 finished defining basic input models and their setup, need to revise the documentation for the input process.

**Comment by jonaslagoni** [comment]
/progress 100 this is considered done. Any extra improvements or changes will be added to the issues of the library itself which can be found [here](https://github.com/asyncapi/generator-model-sdk/issues)
